baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

paginate = 16

[params]
    description = "The fastest blog"
    dateFormat= "Jan 2, 2006"
[taxonomies]
    category = "categories"
    author = "authors"

[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1

[outputs]
home = ["HTML", "JSON"]
